version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001" # Map host port 5000 to container port 5000
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "8080:80" # Map host port 8080 to container port 80

  database:
    image: mongo:latest
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
